Feat/2022
betagouv/evolution_perimetres_geo pull request #43
Opened 2022-02-14 17:03 UTC by Datayama38

2022-02-15 09:07 UTC, nmrgt requested changes

2022-02-15 09:07 UTC, nmrgt commented on etl/src/datasets/custom/common/UpdateDataset.ts
> +      for await (const { op, values, geometries, conditions } of this.transformations) {
faire des opérations métiers en mode "fusion de commune" au lieu de "insert sql"

2022-02-15 09:07 UTC, nmrgt commented on etl/src/datasets.ts
> +import { Perim2022 } from './datasets/custom/Perim2022';
ajouter des tests

2023-07-06 20:20 UTC, jonathanfallon commented
PR obsolète. On ferme ou il faut la mettre à jour ?

2023-07-07 07:00 UTC, closed without merging